name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependencies:
  flutter:
    sdk: flutter
  fl_nodes:
    path: ../

flutter:
  uses-material-design: true