version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "fl_nodes"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
