name: fl_nodes
description: A Flutter package for building node-based editors.
version: 0.1.0
homepage: https://github.com/WilliamKarolDiCioccio/fl_nodes

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_context_menu: ^0.2.0
  keymap: ^0.0.92
  os_detect: ^2.0.3
  tuple: ^2.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"
